### ISSUE TITLE
Temporary directories created without args required in pytest 7.3.0

### ISSUE THREAD

**Issue by natalian98** [charmed-kubernetes/pytest-operator#107]
With the recent update of `pytest` to 7.3.0 (see [changelog](https://github.com/pytest-dev/pytest/releases/tag/7.3.0)), `pytest-operator` in v0.22 is failing in some tests due to an error on setup:
```
Traceback (most recent call last):
  File "/home/runner/work/iam-bundle/iam-bundle/.tox/integration/lib/python3.10/site-packages/pytest_operator/plugin.py", line 149, in tmp_path_factory
    return pytest.TempPathFactory(
TypeError: TempPathFactory.__init__() missing 2 required positional arguments: 'retention_count' and 'retention_policy'
```

Some examples of failing tests:
[cos-lite bundle](https://github.com/canonical/cos-lite-bundle/actions/runs/4663997448/jobs/8255833907#step:5:33)
[iam-bundle](https://github.com/canonical/iam-bundle/actions/runs/4649520715/jobs/8227913025#step:4:29)

A temporary solution is to pin `pytest` to 7.2.2.

**Comment by addyess** [comment]
@natalian98 

Looks like that was resolved with this PR
* https://github.com/charmed-kubernetes/pytest-operator/pull/100

I believe you should see improvement if you use pytest-operator > 0.23.0
