### ISSUE TITLE
Handle charms with merged `metadata.yaml` in `charmcraft.yaml`

### ISSUE THREAD

**Issue by lengau** [charmed-kubernetes/pytest-operator#130]
Charmcraft is moving towards putting all data into charmcraft.yaml - it would be nice if `pytest-operator` supported that too.

From a quick perusal, it looks like simply trying to read the data from `charmcraft.yaml` if `metadata.yaml` doesn't exist would work, as you don't use [any of the keys charmcraft rearranges](https://github.com/canonical/charmcraft/blob/main/charmcraft/models/metadata.py#L62)

**Comment by seb4stien** [comment]
Hasn't it been implemented in e8517da19862953ea63078b51935a277571a9278?

**Comment by addyess** [comment]
Correct.  I think this one is reasonable to be closed
