### ISSUE TITLE
Improve .build_charm return type

### ISSUE THREAD

**Issue by dimaqq** [charmed-kubernetes/pytest-operator#141]
Currently build_charm returns `Optional[Path]` while the comment next to the return statement suggests that it return "one of built paths" (in case of multiple bases).

I suspect that returning None means an error or, alternatively, can never happen,

Meanwhile charm integration tests rely on this function to return a Path, e.g. like so:

```py
      logger.info("Build charm locally")
      charm = await ops_test.build_charm(".")

      logger.info("Refresh the charm")
      await application.refresh(path=charm)
```

I'm proposing that if charm file cannot be found, this function raises an error, and the return type would be a (mandatory) Path.

**Comment by addyess** [comment]
Resolved with #142
