### ISSUE TITLE
Is charm-tools really required?

### ISSUE THREAD

**Issue by dstathis** [charmed-kubernetes/pytest-operator#18]
```
    def check_deps():
        missing = []
        for dep in ("juju", "charm", "charmcraft"):
            res = subprocess.run(["which", dep])
            if res.returncode != 0:
                missing.append(dep)
        if missing:
>           raise RuntimeError(
                "Missing dependenc{}: {}".format(
                    "y" if len(missing) == 1 else "ies",
                    ", ".join(missing),
                )
            )
E           RuntimeError: Missing dependency: charm
```

I ran in to this while trying to set up integration tests. Given that charmcraft basically replaces charm-tools, it would be nice if I didn't need it installed. If we really need both we could install them with pip in the virtualenv automatically.

**Comment by johnsca** [comment]
Yeah, that check should either be dropped or improved to not be required unless actually needed, since we intend the common case going forward to not depend on the old builder.
