### ISSUE TITLE
ops_test fixture cleanup leaky

### ISSUE THREAD

**Issue by PietroPasotti** [charmed-kubernetes/pytest-operator#52]
Not entirely sure yet what the source of the issue is, but it looks like models created by the test fixture are not properly cleaned up when the test is done (or aborted?)

I noticed that I have a bunch of spurious models in my microk8s cloud:
![image](https://user-images.githubusercontent.com/6230162/155307229-7c1aa601-f6e7-4336-bd19-0908fa573d68.png)

Will keep this issue updated if more details emerge; or tell me how I can help make it more helpful because I imagine this isn't of much use.

Update: also juju models seem to hang around. Notice that one of them is stuck in a destroying state since... one week?
```bash
test-charm-l8cp           microk8s/localhost  kubernetes  available   -       admin  2022-02-18   
test-charm-mq6i           microk8s/localhost  kubernetes  available   -       admin  2022-02-18   
test-charm-p9q1           microk8s/localhost  kubernetes  available   -       admin  2022-02-18   
test-kubectl-delete-0rta  microk8s/localhost  kubernetes  available   -       admin  2022-02-18   
test-kubectl-delete-9xne  microk8s/localhost  kubernetes  available   -       admin  5 minutes ago
test-loki-tester-u1n5     microk8s/localhost  kubernetes  destroying  -       admin  2022-02-18   
```

**Comment by ca-scribner** [comment]
I'm guessing maybe these were tests that were `ctrl+c`'d to abort and that cut off the cleanup tasks, but that's just a guess

**Comment by PietroPasotti** [comment]
uhm yes, might have been `ctrl+c`'d
would have expected the cleanup to happen anyway, `finally`-style

**Comment by ca-scribner** [comment]
Again guessing, but I think what happened was multiple `ctrl+c`.  I think it'll catch the first and stop the test but do all the finalization, but if you do multiple it'll break from the finalization as well.  Give that a test and see if you can recreate the orphan models.  If not, something funny is going on

**Comment by PietroPasotti** [comment]
didn't happen again, I'm guessing it was ctrl+c.
