### ISSUE TITLE
pytest-operator 0.17.0 breaks integration tests

### ISSUE THREAD

**Issue by claudiubelu** [charmed-kubernetes/pytest-operator#72]
It seems that the the pytest-operator version 0.17.0 breaks integration tests on teardown.

Failing job without pytest-operator being constrained: https://github.com/claudiubelu/waltz-integration-juju/runs/6065841857?check_suite_focus=true
Job passing after constraining pytest-operator<0.17.0: https://github.com/claudiubelu/waltz-integration-juju/runs/6073143526?check_suite_focus=true

**Comment by addyess** [comment]
`0.18.0` is released -- and resolves this issue
