### ISSUE TITLE
operator should not be bound only to TOX

### ISSUE THREAD

**Issue by beliaev-maksim** [charmed-kubernetes/pytest-operator#92]
please unlock usage without `tox` and provide another tmp path when no `TOX_ENV_DIR` provided

here is a block that causes issue: https://github.com/charmed-kubernetes/pytest-operator/blob/2c29fa889bd57b651aaa5a7c5eba9c1a788433a8/pytest_operator/plugin.py#L146

```python
@pytest.fixture(scope="session")
def tmp_path_factory(request):
    # Override temp path factory to create temp dirs under Tox env so that
    # confined snaps (e.g., charmcraft) can access them.
    return pytest.TempPathFactory(
        given_basetemp=Path(os.environ["TOX_ENV_DIR"]) / "tmp" / "pytest",
        trace=request.config.trace.get("tmpdir"),
        _ispytest=True,
    )
```

**Comment by addyess** [comment]
Should be resolved now.  You may run with `--basetemp=<path>` to put your temporary files wherever you like

**Comment by beliaev-maksim** [comment]
@addyess 
thanks!
